import Head from "next/head";
import Image from "next/image";
import Button from "../components/Button";
import { StepsCard, SymptomCard } from "../components/Cards";
import Container from "../components/Container";
import Navbar from "../components/Navbar";
import HowItWorks from "../containers/HowItWorks";
import OurProposition from "../containers/OurProposition";

import "../styles/index.css";

import LandingPagePic from "public/images/LandingPageSec1/LandingPagePic.svg";

// const Symptoms = [
//   {
//     title: "Anxiety",
//     image: "https://via.placeholder.com/556x370",
//     description:
//       "Our expert team is dedicated to guiding you through the world of medicinal cannabis.",
//   },
//   {
//     title: "Arthritis",
//     image: "https://via.placeholder.com/556x370",
//     description:
//       "Our expert team is dedicated to guiding you through the world of medicinal cannabis.",
//   },
//   {
//     title: "Cancer",
//     image: "https://via.placeholder.com/556x370",
//     description:
//       "Our expert team is dedicated to guiding you through the world of medicinal cannabis.",
//   },
//   {
//     title: "Chronic Pain",
//     image: "https://via.placeholder.com/556x370",
//     description:
//       "Our expert team is dedicated to guiding you through the world of medicinal cannabis.",
//   },
//   {
//     title: "Depression",
//     image: "https://via.placeholder.com/556x370",
//     description:
//       "Our expert team is dedicated to guiding you through the world of medicinal cannabis.",
//   },
//   {
//     title: "Epilepsy",
//     image: "https://via.placeholder.com/556x370",
//     description:
//       "Our expert team is dedicated to guiding you through the world of medicinal cannabis.",
//   },
//   {
//     title: "Insomnia",
//     image: "https://via.placeholder.com/556x370",
//     description:
//       "Our expert team is dedicated to guiding you through the world of medicinal cannabis.",
//   },
//   {
//     title: "Migraines",
//     image: "https://via.placeholder.com/556x370",
//     description:
//       "Our expert team is dedicated to guiding you through the world of medicinal cannabis.",
//   },
//   {
//     title: "Nausea and Vomiting",
//     image: "https://via.placeholder.com/556x370",
//     description:
//       "Our expert team is dedicated to guiding you through the world of medicinal cannabis.",
//   },
// ];
export default function Home() {
  return (
    <div className="mainContainer">
      <Head>
        <title>Purples</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/leaf.svg" />
      </Head>

      {/* <Navbar /> */}

      <main>
        {/* Section 1 */}
        <div className="containerSec1">
          <div className="textArea">
            <div className="heading">
              <span className="headingDiv">Embracing Nature's Remedy: </span>
              <span class="colorHeadingDiv">Medicinal Cannabis </span>
              <span className="headingDiv">for Wellness</span>
            </div>
            <div className="subheading">
              Our expert team is dedicated to guiding you through the world of
              Natural Medicine, empowering you to embrace a natural and
              effective path to optimal well-being.
            </div>
            <div className="button">
              <button className="taBtn">Take Assessment</button>
            </div>
          </div>
          <div className="picArea">
            <Image
              className="landingPic"
              src={LandingPagePic}
              alt="Landing Page Pic"
            />
          </div>
        </div>

        <HowItWorks />

        <OurProposition />
      </main>

      {/* <main className="flex flex-col"> */}
      {/* navbar */}
      {/* first section */}
      {/* <Container
          className="bg-amber-50 sm:h-3/4 sm:pb-16 lg:h-[100vh]"
          id="home"
        >
          <div class="md:my-50 relative z-10 mx-2 flex flex-col justify-between sm:flex-row">
            <div class="lg:min-h-[80vh flex min-h-screen max-w-5xl flex-col justify-center px-0 pt-10 sm:min-h-[80vh] sm:justify-center  sm:pb-10 lg:min-h-screen lg:justify-center">
              <div class="flex flex-col justify-between">
                <h1 class="text-green-90 font-display text-6xl font-bold sm:text-6xl">
                  Embracing Nature's Remedy:
                  <br />
                  <span className="text-[rgba(157,183,138)]">
                    Medicinal Cannabis
                  </span>
                  <br />
                  for Wellness
                </h1>
                <div class="max-w-2xl py-10 text-lg font-medium leading-7 text-green-900">
                  Our expert team is dedicated to guiding you through the world
                  of medicinal cannabis, empowering you to embrace a natural and
                  effective path to optimal well-being.
                </div>

                <div class="flex w-full justify-start ">
                  <Button type={"primary"}>
                    <div class="text-offWhite text-base font-semibold leading-normal">
                      Take a quiz
                    </div>
                  </Button>
                </div>
              </div>
            </div>
          </div>
          <div class="absolute bottom-0 right-0 z-0">
            <Image src="/leaf.svg" width={300} height={300} />
          </div>
        </Container> */}

      {/* second section */}
      {/* <Container className="" id="how-it-works">
          <div className="flex flex-col items-center justify-center p-4">
            <Button type={"neutral"}>
              <div className="flex justify-center text-base font-medium leading-normal text-amber-50">
                How it works
              </div>
            </Button>

            <div className="my-6 justify-center text-center">
              <span className="text-5xl font-bold leading-10 text-amber-50">
                The cure for your health in{" "}
              </span>
              <span className="text-5xl font-bold leading-10 text-emerald-400">
                3&nbsp;simple&nbsp;steps
              </span>
            </div>

            <div className="flex items-center justify-center">
              <div className="grid w-full grid-cols-1 gap-12 py-2 md:grid-cols-2 md:gap-12 lg:grid-cols-3">
              <div className="flex w-full flex-row flex-wrap justify-center gap-5 ">
                <StepsCard
                  step={1}
                  title="Take the Quiz"
                  description="Our expert team is dedicated to guiding you through the world of medicinal cannabis."
                  image="https://via.placeholder.com/556x370"
                />
                <StepsCard
                  step={2}
                  title="Talk to a Doctor"
                  description="Our expert team is dedicated to guiding you through the world of medicinal cannabis."
                  image="https://via.placeholder.com/556x370"
                />
                <StepsCard
                  step={3}
                  title="Get Your Prescription"
                  description="Our expert team is dedicated to guiding you through the world of medicinal cannabis."
                  image="https://via.placeholder.com/556x370"
                />
              </div>
            </div>
          </div>
        </Container>
         */}
      {/* third section */}

      {/* second section */}

      {/* <Container className="" id="our-proposition">
          <div className="flex flex-col justify-start p-4">
            <Button type={"neutral"}>
              <div className="flex justify-center text-base font-medium leading-normal text-amber-50">
                Our Proposition
              </div>
            </Button>

            <div class="relative z-10 mx-2 flex flex-col justify-between sm:flex-row">
              <div class="flex max-w-5xl flex-col justify-center px-0 sm:justify-start lg:justify-center">
                <div class="flex flex-col justify-between">
                  <h1 class="font-display text-5xl font-bold text-amber-50 sm:text-6xl">
                    Take Control of Your Symptoms:
                    <br />
                    Exploring the Benefits of Cannabis
                  </h1>
                </div>
              </div>
            </div>

            <div className="flex items-center justify-center">
              <div className="grid w-full grid-cols-1 gap-12 py-2 md:grid-cols-2 md:gap-12 lg:grid-cols-3">
              <div className="flex w-full flex-row flex-wrap justify-start gap-5 overflow-x-scroll sm:flex-nowrap">
                {Symptoms.map((symptom) => (
                  <SymptomCard
                    title={symptom.title}
                    image={symptom.image}
                    description={symptom.description}
                  />
                ))}
              </div>
            </div>
          </div>
        </Container> */}

      {/* footer */}
      {/* <div class="Rectangle12 w-96 h-96 bg-neutral-950"></div> */}
      {/* </main> */}
    </div>
  );
}
